---
- name: Print Command output
  hosts: all
  gather_facts: false
  tasks:
    - name: Print output
      debug:
        msg:
          - "{{ logging_info_commands }}"
          - "{{ snmp_info_commands }}"
